[build]
  command = "npm install && npm run build"  
  functions = "netlify/functions" 

[dev]
  command = "npm run dev"
  port = 5555
  publish = "dist"
  autoLaunch = true
  framework = "#custom"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"